[book]
authors = ["Soares Chen"]
language = "en"
multilingual = false
src = "content"
title = "Context-Generic Programming Patterns"

[rust]
edition = "2021"

[build]
create-missing = false


[output.html]
default-theme = "rust"