[package]
name = "cgp-patterns"
version = "0.1.0"
edition = "2021"

[dependencies]
cgp = { version = "0.2.0" }
serde = {version = "1", features = ["derive"] }
itertools = "0.11.0"
serde_json = "1"
anyhow = "1"
datetime = "0.5.2"
sha1 = "0.10.6"
reqwest = { version = "0.12.12", features = [ "blocking", "json" ] }