[package]
name = "cgp-patterns"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.11.0"
serde = {version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
cgp = { version = "0.1.0" }